engines_variants = [
    ["Unity", "Unity3D", "Unity Engine", "Unity Pro"],
    ["Unreal Engine", "UE4", "UE5", "Unreal", "UE", "Unreal Development Kit", "UDK"],
    ["Godot", "Godot Engine", "Godot 4", "Godot 3"],
    ["CryEngine", "Crytek Engine", "CryEngine V", "CryEngine 3"],
    ["Cocos2d", "Cocos2d-x", "Cocos2d-x Engine", "Cocos Creator"],
    ["GameMaker", "GameMaker Studio", "GameMaker Studio 2", "GameMaker Engine"],
    ["Construct", "Construct 2", "Construct 3", "Construct Engine"],
    ["RPG Maker", "RPG Maker MV", "RPG Maker VX Ace", "RPG Maker XP", "RPG Maker MZ"],
    ["Source Engine", "Source", "Source SDK", "Source 2"],
    ["Frostbite", "Frostbite Engine", "Frostbite 3"],
    ["Anvil", "Anvil Engine", "AnvilNext", "AnvilNext 2.0"],
    ["Creation Engine", "Creation Kit", "Creation Engine 2"],
    ["Decima Engine", "Decima"],
    ["Roblox", "Roblox Studio", "Roblox Engine"],
    ["Lumberyard", "Amazon Lumberyard", "Lumberyard Engine"],
    ["Stencyl", "Stencyl Engine", "StencylWorks"],
    ["Phaser", "Phaser Engine", "Phaser 3"],
    ["PICO-8", "PICO8", "PICO 8 Fantasy Console"],
    ["Ren'Py", "RenPy", "Ren'Py Engine"],
    ["Panda3D", "Panda Engine"],
    ["Torque3D", "Torque Engine"],
    ["OGRE", "Object-Oriented Graphics Rendering Engine"],
    ["MonoGame", "Mono Game Framework"],
    ["libGDX", "libGDX Framework"],
    ["HaxeFlixel", "Haxe Flixel"],
    ["Flax Engine", "Flax"],
    ["Stride", "Stride Engine", "Xenko"],
    ["Visionaire Studio", "Visionaire Engine"],
    ["GDevelop", "GDevelop Engine"],
    ["CopperCube", "CopperCube Engine"],
    ["Buildbox", "Buildbox Engine"],
    ["Clickteam Fusion", "Fusion", "Clickteam Fusion 2.5"],
    ["OpenRA", "OpenRA Engine"],
    ["GameSalad", "GameSalad Engine"],
    ["Defold", "Defold Engine"],
    ["Banshee Engine", "Banshee"],
    ["Gamebryo", "Gamebryo Engine"],
    ["Hero Engine", "HeroEngine"]
]

engines_enum = [e[0] for e in engines_variants] + ["Any"]

types_variants = [
    ["3D Model", "3D Models", "Model", "Models", "Mesh", "Meshes", "3D Object", "3D Objects"],
    ["Texture", "Textures", "Bitmap", "Bitmaps", "Image Texture", "Image Textures"],
    ["Sprite", "Sprites", "2D Sprite", "2D Sprites", "Sprite Sheet", "Sprite Sheets"],
    ["Animation", "Animated", "Animations", "Motion", "Motions", "Rigged Animation", "Rigged Animations"],
    [
        "VFX", "Visual Effects", "Visual Effect", "Effects", "Effect", "FX", "Visuals", "Visual", "Special Effects",
        "Special Effect", "Particle Effects", "Particle Effect", "Particles"
    ],
    ["UI", "User Interface", "User Interface Elements", "User Interface Element", "HUD", "UI Kit"],
    ["Music", "Musical", "Musical Composition", "Musical Compositions", "Track", "Tracks", "Background Music"],
    ["SFX", "Sound Effects", "Sound Effect", "Sound FX", "Audio Effects", "Audio Effect"],
    ["Soundtrack", "OST", "Original Soundtrack", "Game Soundtrack"],
    ["Voiceover", "VO", "Voice Over", "Voice", "Narration", "Narrations", "Dialogue", "Dialogues"],
    ["Material", "Materials", "Material Preset", "Material Presets"],
    ["Shader", "Shaders", "Shader Graph", "Shader Graphs", "Shader Material", "Shader Materials"],
    ["Blueprint", "Blueprints", "Node Graph", "Node Graphs"],
    ["Script", "Scripts", "Coding", "Code", "Source Code", "Source Codes"],
    ["Plugin", "Plugins", "Add-on", "Add-ons", "Extension", "Extensions"],
    ["Prefab", "Prefabs", "Template", "Templates", "Prototype", "Prototypes"],
    ["Asset", "Assets", "Game Asset", "Game Assets"],
    ["Level", "Levels", "Scene", "Scenes", "Stage", "Stages"],
    ["Map", "Maps", "World Map", "World Maps", "Mini Map", "Mini Maps"],
    ["Environment", "Environments", "World", "Worlds", "Game Environment", "Game Environments"],
    ["Character", "Characters", "NPC", "NPCs", "Player Character", "Player Characters"],
    [
        "Vector", "Vectors", "Vector Graphics", "Vector Graphic", "SVG", "Scalable Vector Graphic",
        "Scalable Vector Graphics"
    ],
    ["Font", "Fonts", "Typeface", "Typefaces", "Text Style", "Text Styles"],
    ["Icon", "Icons", "Icon Set", "Icon Sets"],
    ["Logo", "Logos", "Logo Design", "Logo Designs"],
    ["Cursor", "Cursors", "Pointer", "Pointers"],
    ["Video", "Videos", "Cutscene", "Cutscenes", "Cinematic", "Cinematics"],
    ["Document", "Documents", "Guide", "Guides", "Manual", "Manuals", "Tutorial", "Tutorials"],
    ["Blueprint Function", "Blueprint Functions", "Scripted Function", "Scripted Functions"],
    ["Tilemap", "Tilemaps", "Tile Map", "Tile Maps"],
    ["Audio", "Audios", "Audio File", "Audio Files", "Sound File", "Sound Files"],
    ["Skin", "Skins", "Texture Skin", "Texture Skins"],
    ["Controller", "Controllers", "Input Controller", "Input Controllers"],
    ["Lighting", "Light", "Lights", "Lighting Setup", "Lighting Setups"],
    ["Terrain", "Terrains", "Terrain Asset", "Terrain Assets"],
    ["Physics", "Physics Object", "Physics Objects", "Ragdoll", "Ragdolls"],
]

types_enum = [t[0] for t in types_variants]

genres_variants: list[list[str]] = [
    ["8-Bit", "8-bit", "8 bit", "8bit"],
    ["Pixel Art", "Pixel", "Pixelated", "Pixelation", "Pixelate", "Pixel Art Style"],
    ["Lowpoly", "Low Poly", "Low-poly", "Low Polygons", "Low-Polygons", "Low Polygons Count", "Low-Polygons Count"],
    ["RPG", "Role-Playing Game", "Role Playing Game", "Roleplay", "Roleplay Game"],
    ["RTS", "Real-Time Strategy", "Real Time Strategy", "Realtime Strategy", "Realtime Strategy Game"],
    ["FPS", "First-Person Shooter", "First Person Shooter", "First-Person", "First Person"],
    ["TPS", "Third-Person Shooter", "Third Person Shooter", "Third-Person", "Third Person"],
    ["Sci-Fi", "Science Fiction", "Science-Fiction", "SciFi", "Sci-Fi Game", "Science Fiction Game"],
    ["Fantasy", "Fantasy Game"],
    ["Horror", "Horror Game"],
    ["Survival", "Survival Game"],
    ["Adventure", "Adventure Game"],
    ["Action", "Action Game"],
    ["Puzzle", "Puzzle Game"],
    ["Platformer", "Platformer Game"],
    ["Simulation", "Simulator", "Sim Game"],
    ["Cyberpunk", "Cyberpunk Game"],
    ["Steampunk", "Steampunk Game"],
    ["Casual", "Casual Game"],
    ["Arcade", "Arcade Game"],
    ["Educational", "Educational Game"],
    ["Historical", "Historical Game"],
    ["Medieval", "Medieval Game"],
    ["Space", "Space Game", "Space Simulation", "Space Simulator"],
    ["Western", "Western Game"],
    ["Zombie", "Zombie Game"],
    ["Post-Apocalyptic", "Post Apocalyptic", "Post-Apocalyptic Game"],
    ["Futuristic", "Futuristic Game"],
    ["Military", "Military Game"],
    ["Sports", "Sports Game"],
    ["Racing", "Racing Game", "Racing Simulation"],
    ["MOBA", "Multiplayer Online Battle Arena", "MOBA Game"],
    ["Tower Defense", "Tower Defence", "Tower Defense Game"],
    ["Metroidvania", "Metroidvania Game"],
    ["Roguelike", "Roguelite", "Rogue Game", "Roguelike Game", "Roguelite Game"],
    ["Open World", "Open-World", "Open-World Game"],
    ["Visual Novel", "VN", "Visual Novel Game"],
    ["Tactical", "Tactical Game", "Tactics"],
    ["Turn-Based", "Turn-Based Game", "Turn-Based Strategy"],
    ["Battle Royale", "Battle Royale Game"],
    ["Card Game", "Card", "Card Battle", "Card Battle Game"],
    ["Rhythm", "Rhythm Game", "Music Game"],
    ["VR", "Virtual Reality", "VR Game"],
    ["AR", "Augmented Reality", "AR Game"],
    ["Mystery", "Mystery Game"],
    ["Noir", "Noir Game"],
    ["Anime", "Anime Style", "Anime Game"],
    ["Retro", "Retro Style", "Retro Game"],
    ["Dark Fantasy", "Dark Fantasy Game"],
    ["Mystical", "Mystical Game", "Mysticism"],
    ["Hero Shooter", "Hero Shooter Game"],
    ["Mecha", "Mecha Game", "Mechs", "Mech Game"],
    ["Underwater", "Underwater Game", "Aquatic", "Aquatic Game"],
    ["Exploration", "Exploration Game"],
    ["Idle", "Idle Game"],
    ["Clicker", "Clicker Game"],
    ["4X", "4X Game", "eXplore, eXpand, eXploit, eXterminate"],
]

genres_enum = [g[0] for g in genres_variants]

objects_variants: list[list[str]] = []
